repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.0
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0  # Use the latest version of Mypy
  hooks:
    - id: mypy
      # Instead of types-all, you can add specific type stubs if needed
      # additional_dependencies: [types-all]
      args: [--config-file=mypy.ini]
      # Run mypy on all files, not just modified ones
      pass_filenames: false
      # Alternatively, use this to specify files manually
      # files: ^(your_package|another_package)/.*\.py$